### ISSUE TITLE
Add a NAXSI_FMT / NAXSI_EXLOG helper

### ISSUE THREAD

**Issue by buixor** [nbs-system/spike#10]
Where you can paste a [NAXSI_FMT or NAXSI_EXLOG](https://github.com/nbs-system/naxsi/wiki/naxsilogs), and it would produce a human-compliant explanation.

**Comment by jvoisin** [comment]
Have fun with regular-expressions :/

**Comment by buixor** [comment]
:)

**Comment by jvoisin** [comment]
Done in b26d9e6c9d4a271588c8cd9a8293e35bca97a7a2
