### ISSUE TITLE
make import_ruleset(): use a function to validate and parse a BasicRule / MainRule

### ISSUE THREAD

**Issue by buixor** [nbs-system/spike#11]
(probably should steal from [nxapi](https://github.com/nbs-system/naxsi/tree/master/nxapi))

**Comment by buixor** [comment]
started in a66424a0fd62431f65aade20c1552c002eae662e codes still needs to be smaller & smarter :)

**Comment by jvoisin** [comment]
Done in 77348dd64ab243b3555a4ff03a5044b2112a3b81
