### ISSUE TITLE
Setting storage

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/spike#13]
Settings should go in a simple-stupid ini file, instead of being stored in their own database!

**Comment by mdeous** [comment]
Prefer a basic settings.py, optionally overriden by a prod_settings.py to
prevent versionning sensitive prod data.

**Comment by jvoisin** [comment]
Done in 5b10e8a8d9a81026747e97a650069b29ecbd6d80

Settings are now in config.cfg
