### ISSUE TITLE
What shall we do about flask-bootstrap?

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/spike#23]
[It](https://github.com/mbr/flask-bootstrap/)'s not really used by spike, and we should either remove it, or use it in a more extensive way.

**Comment by jvoisin** [comment]
I vote for removing it.

**Comment by mdeous** [comment]
I vote for keeping it, it would allow us to easily handle flash messages and generate forms with flask-wtf, it also implements pagination helpers using flask-sqlalchemy.
