### ISSUE TITLE
Add a "rule explanator"

### ISSUE THREAD

**Issue by buixor** [nbs-system/spike#3]
Somewhere where you can paste a naxsi rule or whitelist, spike would valid that it's correct :
- ie. no $URL_X mixed with $ARGS_VAR
- ie. no Whitelist with no target mz (but only $URL)

Would prevent a lot of people opening issues :)

**Comment by jvoisin** [comment]
Do we want users to be able to simply _paste a rule and get an explanation for it_, or shall this feature only be available to rules stored in the database?

**Comment by jvoisin** [comment]
Done in e43f38a
