### ISSUE TITLE
Install Spike

### ISSUE THREAD

**Issue by L3V14TH4N** [nbs-system/spike#39]
Hello, dear!!!
I am currently trying to install Spike, however, every time you run the following command: "**python ./spike-server.py init**"  the following message appears

```
/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.
  .format(x=modname), ExtDeprecationWarning
/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/lib64/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "./spike-server.py", line 10, in <module>
    from spike import create_app, version
  File "/usr/local/src/naxsi/spike/spike/__init__.py", line 8, in <module>
    from spike.views import default, rules, rulesets, sandbox, whitelists, whitelistsets
  File "/usr/local/src/naxsi/spike/spike/views/default.py", line 5, in <module>
    from spike.model.naxsi_rules import NaxsiRules
  File "/usr/local/src/naxsi/spike/spike/model/naxsi_rules.py", line 5, in <module>
    from nxapi import rules
ImportError: cannot import name rules
```

Any idea?

**Comment by buixor** [comment]
Hello !

Thanks for giving spike a try, It's still under heavy dev :p
This error seems to be linked to the fact that you don't have [nxapi](https://github.com/nbs-system/nxapi) installed ; the idea behind spike is to be a front-end for the new version of nxapi (thus the dependance).

You should try to run this command to install the needed dependencies:

```
pip -r install requirements.txt
```

**Comment by L3V14TH4N** [comment]
Yes, I run this command in "/spike/nxapi":
python setup.py install

![image](https://cloud.githubusercontent.com/assets/6493983/18671855/0f8d5ddc-7f1c-11e6-9cec-29b6e0962239.png)

and after

![image](https://cloud.githubusercontent.com/assets/6493983/18672007/a2c494bc-7f1c-11e6-96f0-c1dff8d9165b.png)

nxapi it is installed in the same directory of the spike?

**Comment by jvoisin** [comment]
There is no `spike/nxapi` folder.
You should run:

``` bash
$ git clone https://github.com/nbs-system/spike
$ cd spike
$ pip install -r requirements.txt --user
$ python ./spike-server.py init
```

**Comment by L3V14TH4N** [comment]
Afff.. lol, it worked!!!

Tks!!!
