### ISSUE TITLE
Whitelists generates (500 Internal Server Error)

### ISSUE THREAD

**Issue by L3V14TH4N** [nbs-system/spike#40]
Hii, using the Spike, when I tried to generate whitelist this:

`2016/10/05 16:06:59 [error] 6744#0: *854 NAXSI_FMT: ip=200.xxx.xx.xxx&server=www.site.com.br&uri=/umbraco/surface/Common/InformAirportQuery/&learning=0&vers=0.55&total_processed=580&total_blocked=3&block=1&zone0=BODY&id0=16&var_name0=, client: 200.xxx.xx.xxx, server: 10.0.1.101, request: "POST /umbraco/surface/Common/InformAirportQuery/?sdu=CGH HTTP/1.1", host: "www.site.com.br", referrer: "http://www.site.com.br/example/"`

It appeared the following error message:

![image](https://cloud.githubusercontent.com/assets/6493983/19127849/24f704f0-8b17-11e6-9ca8-21a43f5463ea.png)

I believe the problem is in "**var_name0=,**" because when I put it "**var_name0= ,**" problem does not occur.

I would like some opinion.

**Comment by L3V14TH4N** [comment]
**This error still persists!**

**Comment by jvoisin** [comment]
No it doesn't:

![Success]( http://i.imgur.com/yX0PJyc.png )
