### ISSUE TITLE
Problem with rule

### ISSUE THREAD

**Issue by L3V14TH4N** [nbs-system/spike#41]
Hello people.
I'm creating a rule in spike, but it is causing error. 
Follows a log line from my phpbb:

```
2016/11/10 09:44:33 [error] 5568#0: *3 NAXSI_FMT: ip=189.75.xx.yy&server=www.mysite.com.br&uri=/adm/index.php&learning=0&vers=0.55&total_processed=2&total_blocked=1&block=1&cscore0=$SQL&score0=8&zone0=BODY|NAME&id0=1000&var_name0=forum_perm_from&zone1=BODY|NAME&id1=1000&var_name1=update, client: 189.75.xx.yy, server: *.mysite.com.br, request: "POST /adm/index.php?i=acp_forums&sid=044a86d6ab215c09111f0fe905b585fa&icat=7&mode=manage&parent_id=8&action=edit&f=8 HTTP/1.1", host: "www.mysite.com.br", referrer: "http://mysite.com.br/adm/index.php?i=acp_forums&sid=044a86d6ab215c09111f0fe905b585fa&icat=7&mode=manage&parent_id=8&action=edit&f=8"
```

After using the spike, the following rule is generated:

```
BasicRule wl:1000 "mz:$BODY|NAME_VAR:forum_perm_from";
BasicRule wl:1000 "mz:$BODY|NAME_VAR:update";
```
When I restart nginx, the following error message appears:

```
nginx: [emerg] Naxsi-Config : Incorrect line BasicRule wl:1000 (/etc/naxsi/naxsi_src//naxsi_skeleton.c/474)... in /etc/nginx/nginx.conf:38
nginx: configuration file /etc/nginx/nginx.conf test failed
```

any suggestion?

**Comment by jvoisin** [comment]
My bad, should be fixed now.

**Comment by L3V14TH4N** [comment]
Ok, but the error message still persists.

**Comment by jvoisin** [comment]
Aren't different rules generated now?

**Comment by L3V14TH4N** [comment]
No!!! Still the same thing.

**Comment by jvoisin** [comment]
It should be good now.

**Comment by L3V14TH4N** [comment]
Ok, fixed!!!

Thanks ;)

**Comment by L3V14TH4N** [comment]
**Hii, now following rule:**

`2016/11/22 11:38:39 [error] 7592#0: *905 NAXSI_FMT: ip=189.75.xx.yy&server=www.mysite.com.br&uri=/adm/index.php&learning=0&vers=0.55&total_processed=691&total_blocked=1&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1311&var_name0=forum_id[]&zone1=BODY|NAME&id1=1311&var_name1=group_id[0], client: 189.75.xx.yy, server: *.mysite.com.br, request: "POST /adm/index.php?i=acp_permissions&sid=345773296f8ea7104aba8485c576c787&mode=setting_group_local HTTP/1.1", host: "www.mysite.com.br", referrer: "http://www.mysite.com.br/adm/index.php?i=acp_permissions&sid=345773296f8ea7104aba8485c576c787&mode=setting_group_local"` 

**After using the spike, the following rule is generated:**
```
BasicRule wl:1311 "mz:$BODY|NAME_VAR:forum_id[]";
BasicRule wl:1311 "mz:$BODY|NAME_VAR:group_id[0]";
```
**When I restart nginx, the following error message appears:**
```
nginx: [emerg] Naxsi-Config : Incorrect line BasicRule wl:1311 (/etc/naxsi/naxsi_src//naxsi_skeleton.c/474)... in /etc/nginx/nginx.conf:60
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by L3V14TH4N** [comment]
Corrected for:

`BasicRule wl:1311 "mz:BODY|NAME";`
